### ISSUE TITLE
IPv6 capable bootstrappers

### ISSUE THREAD

**Issue by Ape** [ipfs-inactive/ops-requests#10]
Currently all bootstrap peers seem to be IPv4 only. I think there should be at least some IPv6 capable bootstrappers to make IPv6-only peers able to connect to the network.

This might not be very high priority issue, but definitely something I think should be fixed eventually.

**Comment by ghost** [comment]
Word! We definitely want IPv6 everywhere and are tracking the progress in ipfs/infrastructure#88.

I'm closing this request in the meantime since this repo is for specific requests which are immediately actionable and don't need further planning or discussion (see readme)
