### ISSUE TITLE
How to add my cjdns addr to the whitelist for metrics?

### ISSUE THREAD

**Issue by daviddias** [ipfs-inactive/ops-requests#13]
following: 

> http://metrics.i.ipfs.io, and each IPFS node's API. Access control is merely an allowlist of cjdns IPv6 addresses.

https://github.com/ipfs/infrastructure/tree/master/solarnet#overview

**Comment by ghost** [comment]
Sorry @diasdavid this one got totally lost -- you can use one of the public peers in https://github.com/hyperboria/peers, and tell me your IPv6 so I can add it to the allowlist. It's part of secrets.yml thus non-public

**Comment by ghost** [comment]
Closing for now
