### ISSUE TITLE
Updated dist.ipfs.io

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs-inactive/ops-requests#14]
New version at: http://v04x.ipfs.io/ipfs/QmT6pAkgEyfWfAvrg7kQcN6yaMoHQ8Co9WonKiCqzAjsgZ/

Pinned on biham, please pin on some other nodes as well

**Comment by ghost** [comment]
Pinned on the other v04x hosts and updated TXT record

**Comment by dignifiedquire** [comment]
Thanks :octocat:
