### ISSUE TITLE
Add ipget to dist.ipfs.io

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs-inactive/ops-requests#19]
New hash: QmdEgg4GVCgzLyW2hRDedFfhc2Tb92awpvb4wrXUWLpGos

**Comment by dignifiedquire** [comment]
@lgierth can this be closed?

**Comment by ghost** [comment]
I'll close when the pinning is through

**Comment by dignifiedquire** [comment]
looks like pinning happened :)
