### ISSUE TITLE
Deploy project-repos.ipfs.io

### ISSUE THREAD

**Issue by harlantwood** [ipfs-inactive/ops-requests#25]
Github pages is falling over.  So let's host it ourselves.  The hash:

~~QmRTU3Vi1FUZ4MHGP7j8DZJob1rs8quvxHCWe5x7mhtVJJ~~

~~QmQmwZekgo1vBuVf3Zf6DWSZ4Tg1SDM1MNXMccPANigWn9~~

QmXtXME2t8CXZFXSHkdft8CGthMvThmisXuyRU9Yc1HBmC
- [ ] pin on all gateways
- [ ] update dnslink

**Comment by harlantwood** [comment]
~~New, improved, betterer hash: QmQmwZekgo1vBuVf3Zf6DWSZ4Tg1SDM1MNXMccPANigWn9~~

QmXtXME2t8CXZFXSHkdft8CGthMvThmisXuyRU9Yc1HBmC wins.

**Comment by ghost** [comment]
Cool -- could you pin it on the gateways? I failed to pin it earlier because your daemon probably was offline by then. You can just use pinbot in #ipfs: `!pin <hash> project-repos.ipfs.io`

**Comment by harlantwood** [comment]
~~I can see it here: https://v04x.ipfs.io/ipfs/QmQmwZekgo1vBuVf3Zf6DWSZ4Tg1SDM1MNXMccPANigWn9/~~

If that doesn't work for you I'll pin when back at my machine.

**Comment by ghost** [comment]
It might just not have loaded the whole DAG, but only what's been requested through HTTP

**Comment by harlantwood** [comment]
Ah I see.  Will pin soon and update here.

**Comment by harlantwood** [comment]
Merged some PRs and pinned:  QmXtXME2t8CXZFXSHkdft8CGthMvThmisXuyRU9Yc1HBmC

**Comment by ghost** [comment]
It's alive! :) https://project-repos.ipfs.io/

Thanks so much!

**Comment by harlantwood** [comment]
Awesome! Thanks 😃

**Comment by harlantwood** [comment]
Please deploy this new improved version, pinned to gateway: 

QmZ2uFzNj4qKJpBZmC72d8HbjK71kpA1SdreiUR9jQoM6r

Screenshot:

![screenshot 2016-07-07 00 20 56](https://cloud.githubusercontent.com/assets/38769/16681796/b00564ae-44ab-11e6-87e5-33748f0e216f.png)

**Comment by harlantwood** [comment]
Hm, I don't have permissions to re-open this issue... tagging @lgierth ... in the future I can open a new issue per deploy if that's better.

**Comment by ghost** [comment]
> in the future I can open a new issue per deploy if that's better.

Yes please -- this repo is a collection of actionable "could you do X real quick for me?" tasks, so a new issue per task is good.

**Comment by ghost** [comment]
Updated

**Comment by RichardLitt** [comment]
> Yes please -- this repo is a collection of actionable "could you do X real quick for me?" tasks, so a new issue per task is good.

Should we add that to the README, make it clearer?

**Comment by ghost** [comment]
> Should we add that to the README, make it clearer? 

Good call, done
