### ISSUE TITLE
maps.ipfs.io

### ISSUE THREAD

**Issue by davidar** [ipfs-inactive/ops-requests#26]
Could we point maps.ipfs.io to `/ipfs/QmdZxfvkju1saNawPDSBnU6CoFYor2hP8114g4etqwnRTz` ?

OSM would then be accessible via https://maps.ipfs.io/?/ipfs/QmQ2YKnWpfjYQdoDN4KZjxL18K33nz2p8eTHjm5GsY2fnr for instance

**Comment by ghost** [comment]
Thanks @whyrusleeping, I was about to say that I forgot about ops-requests.git, but you were already here :) cc @Kubuxu 

@davidar i'm away for 3 weeks from tomorrow and these two awesome beings ^ are filling in for me

**Comment by whyrusleeping** [comment]
maps.ipfs.io is now CNAMEd to gateway.ipfs.io and has a TXT record of `dnslink=/ipfs/QmdZxfvkju1saNawPDSBnU6CoFYor2hP8114g4etqwnRTz`

**Comment by davidar** [comment]
Thanks @whyrusleeping!
