### ISSUE TITLE
Migrate more bootstrappers to dev040

### ISSUE THREAD

**Issue by ghost** [ipfs-inactive/ops-requests#3]
With the NPM / registry-mirror thing, more people will be using dev0.4.0 and pluto is the only bootstrapper for that, so far.
- [x] disable the respective DNS record entries for ipfs.io, refs.ipfs.io, blog.ipfs.io
- [x] stop ipfs container
- [x] move the existing v2 repo away
- [x] update inventory file
- [x] run ipfs.yml playbook

Should get those before the weekend.

**Comment by jbenet** [comment]
maybe we can have 3 total? not sure. 

(we can also generate temp keys for dev0.4.0 -- add them to the config for now, and run more procs, but that may be more annoying. whatever you pick!)

**Comment by ghost** [comment]
it's pluto uranus and neptune now
