### ISSUE TITLE
dokku for quick development

### ISSUE THREAD

**Issue by daviddias** [ipfs-inactive/ops-requests#31]

**Comment by ghost** [comment]
Ok it's running at `dokku@cloud.ipfs.team` -- anyone who already has access (right now @lgierth and @diasdavid) should be able to add more people via `echo $theSshKey | ssh dokku@cloud.ipfs.team ssh-keys:add $name`.

Your next steps: `ssh dokku@cloud.ipfs.team apps:create webrtc-star` and http://dokku.viewdocs.io/dokku/deployment/application-deployment/

**Comment by daviddias** [comment]
@lgierth this will be a huge time saver, I'm sure @haadcode @VictorBjelkholm and @dignifiedquire will like to know how to take advantage of it, can we have a doc somewhere to make sure this is not lost in a closed issue?

**Comment by drauschenbach** [comment]
Deployment to Dokku is not working for me.

```
installation of dep go-ipfs complete!
mkdir: can't create directory '.git/objects': No such file or directory
remote: The command '/bin/sh -c apk add --update musl-dev gcc go git bash wget ca-certificates 	&& mkdir -p $IPFS_PATH 	&& adduser -D -h $IPFS_PATH -u 1000 ipfs 	&& chown ipfs:ipfs $IPFS_PATH && chmod 755 $IPFS_PATH 	&& go get -u github.com/whyrusleeping/gx 	&& go get -u github.com/whyrusleeping/gx-go 	&& ([ -z "$GX_IPFS" ] || echo $GX_IPFS > $IPFS_PATH/api) 	&& cd $SRC_PATH 	&& gx --verbose install --global 	&& mkdir .git/objects && commit=$(git rev-parse --short HEAD) 	&& echo "ldflags=-X github.com/ipfs/go-ipfs/repo/config.CurrentCommit=$commit" 	&& cd $SRC_PATH/cmd/ipfs 	&& go build -ldflags "-X github.com/ipfs/go-ipfs/repo/config.CurrentCommit=$commit" 	&& cp ipfs /usr/local/bin/ipfs 	&& cp $SRC_PATH/bin/container_daemon /usr/local/bin/start_ipfs 	&& chmod 755 /usr/local/bin/start_ipfs 	&& apk del --purge musl-dev gcc go git && rm -rf $GOPATH && rm -vf $IPFS_PATH/api' returned a non-zero code: 1
```

**Comment by ghost** [comment]
@drauschenbach could you file that as an issue in ipfs/go-ipfs? This issue here is not about go-ipfs

**Comment by drauschenbach** [comment]
Filed https://github.com/ipfs/go-ipfs/issues/3614
