### ISSUE TITLE
*.ipfs.io domain for discourse

### ISSUE THREAD

**Issue by ghost** [ipfs-inactive/ops-requests#33]
Right now it's ipfs.trydiscourse.com -- @RichardLitt @flyingzumwalt should it be forum.ipfs.io or community.ipfs.io?

**Comment by flyingzumwalt** [comment]
I'd be happy with either. I lean towards forum.ipfs.io

**Comment by ghost** [comment]
> I lean towards forum.ipfs.io

Yeah I'm thinking the same

**Comment by RichardLitt** [comment]
forum is better. :)

**Comment by lidel** [comment]
`<bikeshed>` `hivemind.ipfs.io` `</bikeshed>` 🙃 

Jokes aside, some subdomain ideas: 
https://meta.discourse.org/t/naming-the-subdomain-discourse-runs-on/16109

In general, the most popular ones I've seen across the web:
```
talk.ipfs.io 
forum.ipfs.io
community.ipfs.io
```

**Comment by Kubuxu** [comment]
I think we were thinking about `discuss.ipfs.io`.

**Comment by ghost** [comment]
this is done: https://discuss.ipfs.io
