### ISSUE TITLE
Create local-gateway.ipfs.team

### ISSUE THREAD

**Issue by Kubuxu** [ipfs-inactive/ops-requests#40]
For use of internal gateway overriding or our infrastructure. It should point to invalid IP, `0.42.42.42` should work.

----

Why invalid IP? Because in places were I want to use it with HTTP and I don't want to have this connection exit the host.

----

This domain is for internal infrastructure usage, do not use it as your own gateway address.

**Comment by ghost** [comment]
Done, sorry for the delay -- you can do it directly in DO too if you have access. Btw, I'm more and more leaning towards running our own DNS now that there's the Anycast option :)
