### ISSUE TITLE
Create an @ipfs.io account for flyingzumwalt

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs-inactive/ops-requests#41]
I need an @ipfs.io account so I can edit things on the community calendar. Who is able to create them?

Address: matt@ipfs.io or flyingzumwalt@ipfs.io
Please also grant that account permission to edit the community calendar.

**Comment by ghost** [comment]
do you still need this done?

**Comment by flyingzumwalt** [comment]
I got one. Thank you.
