### ISSUE TITLE
Update project-repos

### ISSUE THREAD

**Issue by RichardLitt** [ipfs-inactive/ops-requests#42]
https://ipfs.io/ipfs/QmSkvFokbXf95VLfpYGhjZqosp7Eiiqi8nPLdtQndxWZhj/

**Comment by ghost** [comment]
I made it QmSkvFokbXf95VLfpYGhjZqosp7Eiiqi8nPLdtQndxWZhj because you pinned that in IRC just a minute later.

**Comment by RichardLitt** [comment]
Yep. Updated it above. Thanks!
