### ISSUE TITLE
Castor access

### ISSUE THREAD

**Issue by daviddias** [ipfs-inactive/ops-requests#5]
Hi!

I'm currently 'out' of Castor (probably my home was deleted in the migration?), can I have access again? It seems Castor is not publishing the IPNS record necessary for registry-mirror anymore

Thank you :)

**Comment by ghost** [comment]
Closing this since castor went up in a big fire :/

**Comment by jbenet** [comment]
i've been waiting to use this

![](https://media.giphy.com/media/rn79UlSTDfDlS/giphy.gif)

**Comment by ghost** [comment]
@jbenet you have jbenet@<host>.i.ipfs.io where host is one of biham, nihal, pollux. sirius and castor are full and broken, respectively.
