### ISSUE TITLE
Launch protocol.ai

### ISSUE THREAD

**Issue by jesseclay** [ipfs-inactive/ops-requests#53]
Site is ready, need to launch Protocol.ai.

@lgierth what's the process for this? I can get it compiled into a hugo static directory. Then just send it over to you?

**Comment by ghost** [comment]
Isn't it in protocol/website.git?

**Comment by jesseclay** [comment]
Yep!

2017-03-28 6:22 GMT-07:00 Lars Gierth <notifications@github.com>:

**Comment by ghost** [comment]
Cool cool then I got it

**Comment by ghost** [comment]
done: https://protocol.ai
