### ISSUE TITLE
redirect ipn.io -> protocol.ai

### ISSUE THREAD

**Issue by jesseclay** [ipfs-inactive/ops-requests#55]
once protocol.ai is up, we'll want to take down ipn.io (RIP) and redirect to protocol.ai

**Comment by ghost** [comment]
I need access to whereever ipn.io is

**Comment by ghost** [comment]
Same for protocol.ai

**Comment by jesseclay** [comment]
@jbenet ^^^

2017-03-28 6:24 GMT-07:00 Lars Gierth <notifications@github.com>:

**Comment by jesseclay** [comment]
@jbenet  mind redirecting ipn.io -> protocol.ai?

**Comment by ghost** [comment]
this is done
