### ISSUE TITLE
Deploy new version of archives.ipfs.io

### ISSUE THREAD

**Issue by eminence** [ipfs-inactive/ops-requests#56]
Can you please deploy [`QmZ3bK5nsPAdHcsaVV12eN5obgvLKgJmJrodKYxNHPE7To`](https://ipfs.io/ipfs/QmZ3bK5nsPAdHcsaVV12eN5obgvLKgJmJrodKYxNHPE7To/) to https://archives.ipfs.io/ ?

This updated hash reflects the contents of [c7d23567](https://github.com/ipfs/archives/commit/c7d23567d7405f0bc6a460f36e5f390a5e029533)

Timeframe: sometime this week (low priority)

**Comment by Kubuxu** [comment]
I just merged cdnjs update so we should update the hash.

**Comment by eminence** [comment]
The new hash to deploy is now [QmeYtxqWa5zGSTGANjm7CEQJth6qfnkDwVd7Fvs5qMmksP](https://ipfs.io/ipfs/QmeYtxqWa5zGSTGANjm7CEQJth6qfnkDwVd7Fvs5qMmksP) 

This reflects the contents of ipfs/archives@9fea16e1127ce3512fb047c491ebf66cc4e2e11f

**Comment by ghost** [comment]
ok! https://archives.ipfs.io
