### ISSUE TITLE
Access to the ipfsbot account in Meldium

### ISSUE THREAD

**Issue by chriscool** [ipfs-inactive/ops-requests#7]
In https://github.com/ipfs/go-ipfs/pull/2072, @jbenet wrote:

> @chriscool the account is ipfsbot, the pw should be in meldium-- if it doesnt work, open an issue in https://github.com/ipfs/ops-requests/

It looks like I don't have access to the ipfsbot account anymore when I am logged into meldium.

**Comment by ghost** [comment]
@jbenet not sure, I don't have access either -- it's listed under "available accounts"

**Comment by jbenet** [comment]
@chriscool you should have access (from your email @tuxfamily) -- do you see the account there?

@lgierth I default to setting the things in the "IPFS Team" (not Protocol) as "can request access" that way we can easily add new people in the community to meldium for single accounts without granting all the things right out. i can make a subteam for core with access to the all the things

**Comment by chriscool** [comment]
Yeah it works now with my @tuxfamily email! Thanks @jbenet!
