### ISSUE TITLE
Upgrade IPFS node in Biham to latest 0.4.0

### ISSUE THREAD

**Issue by daviddias** [ipfs-inactive/ops-requests#8]
I believe that @lgierth already updated the binary on @whyrusleeping's request, however it seems that the process running there is still the old 0.4.0 because it is currently deadlocked. Can someone verify and restart the process with the latest 0.4.0 branch please? Thank you :)

**Comment by daviddias** [comment]
@whyrusleeping fixed it :D

**Comment by ghost** [comment]
mh okay what did you do? I'm pretty sure it did restart into the new revision last night.

**Comment by whyrusleeping** [comment]
@lgierth the issue was that the files api stuff was borked and needed to be refreshed

**Comment by ghost** [comment]
yeah but what did you do after I deployed last night?

**Comment by ghost** [comment]
I bumped biham to ipfs/go-ipfs@1c1f9c6dd860c56c274e721ff0e057708836cd80 in ipfs/infrastructure@a0353a7f46924c4f6af41428ead058668501f635 last night

**Comment by whyrusleeping** [comment]
i did `ipfs files rm -r /npm-registry`

**Comment by ghost** [comment]
Oh okay -- thanks!
