### ISSUE TITLE
Point project-repos.ipfs.io to GH Pages

### ISSUE THREAD

**Issue by ghost** [ipfs-inactive/ops-requests#9]
cc @harlantwood

Will A records do, as describe in https://help.github.com/articles/tips-for-configuring-an-a-record-with-your-dns-provider/ ?

Fixes ipfs/project-repos#27

**Comment by ghost** [comment]
I did it using A records for now, seems to work ok: http://project-repos.ipfs.io/

**Comment by harlantwood** [comment]
Super, thanks @lgierth!
